[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_raffle = "3EqTRzYX1UTiXckfNn1kPronmoB7QYT3gnPoPuEsqZ5c"
solana_poker = "7EZ1zWNMjuHh62dikk9TAo478VMzAiLkvg8S7Vm85T7s"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=19e8e7a6-48a7-405a-95d6-27123b062c3d"


[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=19e8e7a6-48a7-405a-95d6-27123b062c3d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
